[package]
name = "reqwest-actix-stream"
version = "1.1.1"
authors = ["clia <clia@163.com>"]
edition = "2018"

[lib]
name = "reqwest_actix_stream"
crate-type = ["rlib"]

[dependencies]
actix-web = "4"
futures = "0.3"
actix-http = "3"
reqwest = "0.11"
