[package]
name = "reqwest-actix-stream"
version = "1.0.0"
authors = ["clia <clia@163.com>"]
edition = "2018"

[lib]
name = "reqwest_actix_stream"
crate-type = ["rlib"]

[dependencies]
actix-web = "3"
futures = "0.3"
actix-http = "2"
reqwest = "0"
